### ISSUE TITLE
Create the event page

### ISSUE THREAD

**Issue by Tydomx** [Tydomx/barkr-meetup#8]
Create event page with moment.js or something similar

**Comment by anjulituck** [comment]
Depending on time, this might be something to add after the presentation. However, I am excited to add this feature soon!

**Comment by anjulituck** [comment]
Added an events page to embed Google Calendar and a linked button to an new events form. We are still seeing if we can incorporate a node app for the form but we will see.

**Comment by Tydomx** [comment]
Still working on bulma formatting, but google calendar has been embedded

**Comment by anjulituck** [comment]
Adding google form that updates calendar
