### ISSUE TITLE
Create Log-in page

### ISSUE THREAD

**Issue by Tydomx** [Tydomx/barkr-meetup#9]
With handlebars create a log in page for users to log into the app

**Comment by anjulituck** [comment]
Styling with Handlebars, setup for sessions and Bulma help are almost done. Next move is to see why the event handlers are not working for the login and sign up buttons.

**Comment by anjulituck** [comment]
- Updated the navbar to be mobile responsive with nav burger dropdown
- Will need to update Barkr logo button icons once branding done
